# Configure json files
---

- name: Create config.json
  template:
    src=config.json.j2
    dest=/etc/sensu/config.json
    owner=sensu
    group=sensu
    backup=yes
    mode=0644
  notify: 
    - restart sensu-api
  when: sensu_server_boolean == true
  notify:
    - restart sensu-server
  when: sensu_server_boolean == true 

- name: Create client.json
  template:
    src=client.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner=sensu
    group=sensu
    backup=yes
    mode=0644
  notify:
    - restart sensu-client
